font_family      JetBrainsMono Nerd Font
font_size        8.5
window_padding_width 10

background       #0A0600
foreground       #D4AF37

cursor           #E5A91A
selection_background #E5A91A
selection_foreground #0A0600

active_border_color #E5A91A
inactive_border_color #6A541C

enable_audio_bell no
hide_window_decorations yes

confirm_os_window_close 0


